version: '3.4'

services:
  mylinebot:
    container_name: mylinebot
    image: mylinebot
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - "linebot.env"
    volumes:
      - ".:/app"

  localtunnel:
    container_name: localtunnel
    image: efrecon/localtunnel
    links:
      - mylinebot
    env_file:
      - "linebot.env"
    depends_on:
      - mylinebot
    command:
      --local-host mylinebot --port 5000 --subdomain tanaline
